# Generated by Django 4.2 on 2024-09-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userotpcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotpcode',
            old_name='is_user',
            new_name='is_used',
        ),
    ]
