# Generated by Django 4.2 on 2024-09-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
