# Generated by Django 4.2 on 2024-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_option_question_userquestionchoice_option_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionchoice',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='asas'),
            preserve_default=False,
        ),
    ]
