# Generated by Django 4.2 on 2024-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_userquestionchoice_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionchoice',
            name='option',
        ),
        migrations.AddField(
            model_name='userquestionchoice',
            name='option',
            field=models.ManyToManyField(to='account.option'),
        ),
    ]
