# Generated by Django 4.2 on 2024-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_userquestionchoice_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionchoice',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, to='account.option'),
        ),
    ]
