# Generated by Django 4.2 on 2024-09-23 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userquestionchoice_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionchoice',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userquestionchoice',
            unique_together={('question', 'user')},
        ),
    ]
