# Generated by Django 4.2 on 2024-09-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userquestionchoice_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionchoice',
            name='option',
        ),
        migrations.AddField(
            model_name='userquestionchoice',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.option'),
        ),
    ]
