# Generated by Django 4.2 on 2024-09-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_subcategory_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='Lesson',
        ),
    ]
